### ISSUE TITLE
UI blocking during refresh balance in buyer side

### ISSUE THREAD

**Issue by W3-Anjan** [w3-engineers/viper#10]
## I'm submitting a ...

  - [x] feature request
  - [ ] support request

## Expected Behavior

In wallet page infinity progress dialog showing during refresh balance

**Comment by W3-Mimo** [comment]
Hello
1. Remove timeout functionality for refresh balance
2. Add a common progress dialog for wallet page and show it using a time handler
3. Add UI callback from buyer and seller manager to wallet manager then add it from wallet manager to wallet activity
4. Refactoring code base

Thanks.
