### ISSUE TITLE
Prepare communication channel for Dataplan

### ISSUE THREAD

**Issue by W3-Anjan** [w3-engineers/viper#4]
## I'm submitting a ...

  - [x] feature request
  - [ ] support request

## Expected Behavior

Prepare API observer for Dataplan and application end users

**Comment by W3-Mimo** [comment]
Hello
- Refactoring data plan part
- Preparing a hierarchy protocol for accessing data in data plan and application sided UI

Thanks.

**Comment by W3-Mimo** [comment]
Hello
1. Update API calling mechanism
2. Remove dependency with database, preference and purchase section
3. maintain hierarchy for communication channel

Thanks.

**Comment by W3-Mimo** [comment]
Hello,
Service layer vice versa calling process has been added in client library part.

Thanks.
